import { FileText, Search, Filter } from 'lucide-react';

export default function BulletinsPage() {
  const bulletins = [
    {
      date: 'TODAY',
      items: [
        { time: '10:15 AM', tag: 'TOP PICK', tagColor: 'bg-danger text-white', title: 'Hyderabad Race 6: Thunder Star', desc: 'Our AI model indicates a 72% win probability for Thunder Star, well above the implied odds.', number: '1', numColor: 'text-danger border-danger/30' },
        { time: '09:30 AM', tag: 'VALUE BET', tagColor: 'bg-primary text-white', title: 'Bangalore Race 4: Royal Empress', desc: 'Despite poor form on paper, our hidden metrics show strong potential for an upset here.', number: '2', numColor: 'text-primary border-primary/30' },
        { time: '08:00 AM', tag: 'TRACK UPDATE', tagColor: 'bg-success/20 text-success border border-success/30', title: 'Mumbai Track Condition: Good to Firm', desc: 'No overnight rain. Track is playing fast, favoring front runners today.' },
      ]
    },
    {
      date: 'YESTERDAY',
      items: [
        { time: '11:45 AM', tag: 'JOCKEY INSIGHT', tagColor: 'bg-secondary/20 text-secondary border border-secondary/30', title: 'A. Singh on Fire', desc: 'A. Singh has won 3 of his last 5 rides. Our model upgrades all his mounts today.' },
        { time: '09:00 AM', tag: 'LAY OF THE DAY', tagColor: 'bg-warning text-white', title: 'Pune Race 2: Silver Charm', desc: 'Overbet favorite. Our models show significant vulnerabilities at the distance.', number: '4', numColor: 'text-warning border-warning/30' },
      ]
    }
  ];

  return (
    <div className="container mx-auto px-4 py-12 relative z-10">
      <div className="flex flex-col md:flex-row md:items-end justify-between mb-12 gap-6">
        <div className="max-w-2xl">
          <h1 className="text-3xl font-heading font-bold uppercase tracking-wide flex items-center gap-3">
            <FileText className="w-8 h-8 text-primary" />
            Daily AI Bulletins
          </h1>
          <p className="text-textSecondary mt-3 text-sm leading-relaxed">
            Bite-sized, actionable insights generated by our AI engine throughout the day.
          </p>
        </div>
        
        <div className="flex items-center gap-3">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-textSecondary" />
            <input 
              type="text" 
              placeholder="Search bulletins..." 
              className="bg-surface border border-border rounded-lg pl-10 pr-4 py-2 text-sm focus:outline-none focus:border-primary transition-colors"
            />
          </div>
          <button className="flex items-center gap-2 bg-surface border border-border rounded-lg px-4 py-2 text-sm hover:bg-card transition-colors">
            <Filter className="w-4 h-4" />
            Filter
          </button>
        </div>
      </div>

      <div className="max-w-4xl mx-auto space-y-12">
        {bulletins.map((day, idx) => (
          <div key={idx}>
            <div className="flex items-center gap-4 mb-6">
              <h2 className="text-sm font-bold text-textSecondary uppercase tracking-widest">{day.date}</h2>
              <div className="flex-1 h-px bg-border/50" />
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {day.items.map((bulletin, i) => (
                <div 
                  key={i} 
                  className="group relative bg-card border border-border rounded-xl p-6 hover:border-primary/50 hover:shadow-soft transition-all duration-300 flex flex-col h-full overflow-hidden"
                >
                  <div className="absolute -bottom-8 -right-8 w-32 h-32 bg-white/5 rounded-full blur-2xl pointer-events-none group-hover:bg-primary/10 transition-colors" />

                  <div className="flex items-center justify-between mb-4 relative z-10">
                    <span className="text-[10px] text-textSecondary font-bold tracking-wider">{bulletin.time}</span>
                    <span className={`text-[9px] font-bold px-2 py-1 rounded tracking-wider ${bulletin.tagColor}`}>
                      {bulletin.tag}
                    </span>
                  </div>

                  <h4 className="font-heading font-bold text-lg mb-3 relative z-10 group-hover:text-primary transition-colors">{bulletin.title}</h4>
                  <p className="text-sm text-textSecondary mb-6 flex-1 relative z-10 leading-relaxed">{bulletin.desc}</p>
                  
                  <div className="flex items-center justify-between mt-auto relative z-10 pt-4 border-t border-border/50">
                    <button className="text-primary text-xs font-bold uppercase tracking-wider flex items-center gap-1 group/btn hover:text-secondary transition-colors">
                      Read Full Report 
                      <span className="group-hover/btn:translate-x-1 transition-transform">→</span>
                    </button>
                    
                    {bulletin.number && (
                      <div className={`w-8 h-8 rounded-full border ${bulletin.numColor} flex items-center justify-center`}>
                        <span className="font-heading font-bold">{bulletin.number}</span>
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
